apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: dependency-watchdog-weeder
  name: dependency-watchdog-weeder-config
data:
  dep-config.yaml: |
    watchDuration: 5m0s
    servicesAndDependantSelectors:
      etcd-main-client:
        podSelectors:
          - matchExpressions:
              - key: gardener.cloud/role
                operator: In
                values:
                  - controlplane
              - key: role
                operator: In
                values:
                  - apiserver
      kube-apiserver:
        podSelectors:
          - matchExpressions:
              - key: gardener.cloud/role
                operator: In
                values:
                  - controlplane
              - key: role
                operator: NotIn
                values:
                  - main
                  - apiserver