---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - endpoints
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - gardener.cloud
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gardener.cloud
  resources:
  - clusters/status
  verbs:
  - get
